const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.destroy,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{DarAVolta: 0},
	{Projétil: 0},
	{espaco: 0},
	{sensor: 0},
	{Senóide: 0},
	{gerador: 0},
	{DestruirForaDoLayout: 0},
	{tiro: 0},
	{inimigo: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{piloto: 0},
	{Teclado: 0},
	{Pontuação: 0},
	{explosão: 0},
	{Sprite: 0},
	{Botão: 0},
	{Titulo: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Texto: 0},
	{Áudio: 0},
	{VARcontaTiro: 0}
];

self.InstanceType = {
	espaco: class extends self.ISpriteInstance {},
	sensor: class extends self.ISpriteInstance {},
	gerador: class extends self.ISpriteInstance {},
	tiro: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	piloto: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Pontuação: class extends self.ITextInstance {},
	explosão: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Titulo: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {}
}